# Legacy configuration file - DEPRECATED
# ⚠️ This file is kept for backward compatibility only
# 
# USE INSTEAD:
# - configs/training.yaml (for model training - Rohit)
# - configs/evaluation.yaml (for evaluation - Kush)
#
# This separation prevents merge conflicts between partners.

language: "python"

# Pointer to split configs
training_config: "./configs/training.yaml"
evaluation_config: "./configs/evaluation.yaml"
